version: "3"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - USE_CORS=${USE_CORS}
      - REFRESH_TOKEN_IN_BODY=${REFRESH_TOKEN_IN_BODY}
      - REFRESH_TOKEN_IN_COOKIE=${REFRESH_TOKEN_IN_COOKIE}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS}
    depends_on:
      - postgres
  postgres:
    image: postgres 
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - fastapi-blog:/var/lib/postgresql/data 

volumes:
  fastapi-blog: